import "./globals.css";
import { Inter } from "next/font/google";
import ModalProvider from "@/providers/ModalProvider";
import getCurrentUser from "@/actions/getCurrentUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Netflix clone",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <ModalProvider currentUser={currentUser} />
        {children}
      </body>
    </html>
  );
}
